import "./style.css"
// import javascriptLogo from "./javascript.svg"
// import viteLogo from "/vite.svg"
import "./menu-toogler"
import "./modal"
import "./anchor-link-smooth"
import "./carousel"
import "./accordion"
